SUPER_ADMIN = 1
ADMIN = 2
ENTREPRENEUR = 3
JOBSEEKER = 5

roles_data = ((SUPER_ADMIN,'SUPER_ADMIN'),(ADMIN,'ADMIN'),(ENTREPRENEUR,'EMPLOYER'),(JOBSEEKER,'JOBSEEKER'))
roles_data_dict = dict(roles_data)
