# Generated by Django 4.2.13 on 2024-06-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_social_media', to='company.company')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_social_media', to='socialmedia.socialmedia')),
            ],
        ),
    ]
