# Generated by Django 4.2.13 on 2024-06-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_companysocialmedia_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/images'),
        ),
    ]
