# Generated by Django 4.1 on 2024-06-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_alter_jobs_company'),
        ('jobbookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsbookmark',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='job.jobs'),
        ),
    ]
