# Generated by Django 4.2.13 on 2024-06-20 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('not_type', models.CharField(choices=[('sticky', 'Sticky'), ('push', 'Push'), ('admin_push', 'admin_push')], default='push', max_length=200, null=True)),
                ('notification_type', models.CharField(max_length=200, null=True)),
                ('notification_message', models.CharField(max_length=200, null=True)),
                ('message_description', models.TextField(null=True)),
                ('path', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHaveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_have_notifications', to='notification.notification')),
                ('to_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_have_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='to_notification',
            field=models.ManyToManyField(through='notification.UserHaveNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
