# Generated by Django 4.2.13 on 2024-06-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='file',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
