# Generated by Django 4.1 on 2024-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='file',
            field=models.FileField(null=True, upload_to='notification/files'),
        ),
    ]
