# Generated by Django 4.2.13 on 2024-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhavenotification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
