# Generated by Django 4.2.13 on 2024-07-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetup',
            name='email_address',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='emailsetup',
            name='password',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='emailsetup',
            name='smtp_server_address',
            field=models.CharField(max_length=300),
        ),
    ]
