# Generated by Django 4.1 on 2024-02-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SUPER_ADMIN'), (2, 'ADMIN'), (3, 'ENTREPRENEUR'), (5, 'EMPLOYER')], null=True),
        ),
    ]
