# Generated by Django 4.1 on 2024-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SUPER_ADMIN'), (2, 'ADMIN'), (3, 'ENTREPRENEUR'), (5, 'JOBSEEKER')], null=True),
        ),
    ]
