# Generated by Django 4.2.13 on 2024-06-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SUPER_ADMIN'), (2, 'ADMIN'), (3, 'EMPLOYER'), (5, 'JOBSEEKER')], null=True),
        ),
    ]
