# Generated by Django 4.2.13 on 2024-06-19 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '__first__'),
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(null=True, upload_to='users/jobseeker/cv')),
                ('experience', models.PositiveIntegerField()),
                ('about', models.TextField()),
                ('address_1', models.CharField(max_length=450)),
                ('address_2', models.CharField(blank=True, default='', max_length=450, null=True)),
                ('interest', models.ManyToManyField(related_name='jobseekers_interests', to='job.jobcategory')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobseekers', to='professions.profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerHaveSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(blank=True, default=1)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobseekerhaveskills',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_have_skills'),
        ),
    ]
