# Generated by Django 4.1 on 2024-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_jobsapply_unique_user_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
