# Generated by Django 4.1 on 2024-04-23 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('jobseeker', '0002_jobseeker_delete_employer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerHaveSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(related_name='jobseekers', through='jobseeker.JobSeekerHaveSkills', to='job.skills'),
        ),
        migrations.DeleteModel(
            name='EmployerHaveSkills',
        ),
        migrations.AddField(
            model_name='jobseekerhaveskills',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseeker'),
        ),
        migrations.AddField(
            model_name='jobseekerhaveskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.skills'),
        ),
    ]
