# Generated by Django 4.1 on 2024-05-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_jobseeker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsapply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
