# Generated by Django 4.1 on 2024-05-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_jobseekerhaveskills_jobseeker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerhaveskills',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_skills', to='jobseeker.jobseeker'),
        ),
    ]
