# Generated by Django 4.1 on 2024-05-20 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0008_jobs_status'),
        ('jobseeker', '0009_alter_jobseekerhaveskills_jobseeker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=1500)),
                ('cv', models.FileField(null=True, upload_to='users/jobseeker/images')),
                ('expected_salary', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobseekers', to='job.jobcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=1500)),
                ('designation', models.CharField(max_length=1000)),
                ('joined_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('still_work', models.BooleanField(default=False)),
                ('job_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_experience', to='job.jobcategory')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='jobseekerhaveskills',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
