# Generated by Django 4.1 on 2024-05-20 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0001_initial'),
        ('jobseeker', '0010_professionalinformation_workexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerhaveskills',
            name='experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MySocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to=settings.AUTH_USER_MODEL)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_socialmedia', to='socialmedia.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=2000)),
                ('degree_name', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=1500)),
                ('education_level', models.CharField(max_length=1000)),
                ('joined_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
