# Generated by Django 4.1 on 2024-05-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0011_alter_jobseekerhaveskills_experience_mysocialmedia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='jobseeker',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='jobseekerhaveskills',
            old_name='jobseeker',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mysocialmedia',
            old_name='jobseeker',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='jobseeker',
            new_name='user',
        ),
    ]
