# Generated by Django 4.1 on 2024-05-22 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobs_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0012_rename_jobseeker_education_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalinformation',
            name='about',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalinformation',
            name='address_1',
            field=models.CharField(default='', max_length=450),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionalinformation',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='professionalinformation',
            name='interest',
            field=models.ManyToManyField(related_name='jobseekers_interests', to='job.jobcategory'),
        ),
        migrations.AlterField(
            model_name='professionalinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
