# Generated by Django 4.1 on 2024-05-22 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_profession'),
        ('jobseeker', '0013_professionalinformation_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalinformation',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobseekers', to='job.profession'),
        ),
    ]
