# Generated by Django 4.1 on 2024-05-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0014_professionalinformation_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalinformation',
            name='job_category',
        ),
    ]
