# Generated by Django 4.1 on 2024-05-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('jobseeker', '0015_remove_professionalinformation_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalinformation',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobseekers', to='professions.profession'),
        ),
    ]
