# Generated by Django 4.1 on 2024-05-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0018_remove_mysocialmedia_social_media_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobsBookmark',
        ),
    ]
