# Generated by Django 4.1 on 2024-05-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0022_remove_professionalinformation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerhaveskills',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
