# Generated by Django 4.1 on 2024-05-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0023_alter_jobseekerhaveskills_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalinformation',
            name='cv',
            field=models.FileField(null=True, upload_to='users/jobseeker/cv'),
        ),
    ]
