# Generated by Django 4.1 on 2024-05-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0024_alter_professionalinformation_cv'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobseekerhaveskills',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_have_skills'),
        ),
    ]
