# Generated by Django 4.1 on 2024-05-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='company_name',
        ),
    ]
