# Generated by Django 4.2.13 on 2024-06-25 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_education_is_currently'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
