# Generated by Django 4.2.13 on 2024-06-19 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_slug', models.CharField(max_length=200, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/images')),
                ('company_banner', models.ImageField(blank=True, null=True, upload_to='company/images')),
                ('about', models.TextField(blank=True, null=True)),
                ('company_size', models.CharField(max_length=350, null=True)),
                ('website', models.URLField(max_length=300, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=950, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_companies', to=settings.AUTH_USER_MODEL)),
                ('type', models.ManyToManyField(related_name='companiess', to='company.companytype')),
            ],
        ),
    ]
