# Generated by Django 4.2.13 on 2024-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
