# Generated by Django 4.1 on 2024-05-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='company',
            name='company_banner',
            field=models.ImageField(default='', upload_to='company/images'),
            preserve_default=False,
        ),
    ]
