# Generated by Django 4.2.13 on 2024-06-25 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
