# Generated by Django 4.1 on 2024-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(related_name='companiess', to='company.companytype'),
        ),
    ]
