# Generated by Django 4.1 on 2024-06-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_banner',
            field=models.ImageField(blank=True, null=True, upload_to='company/images'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/images'),
        ),
    ]
