# Generated by Django 4.2.13 on 2024-06-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobutils', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosition',
        ),
    ]
