# Generated by Django 4.2.13 on 2024-06-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobutils', '0003_educationlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationLevel',
        ),
    ]
