# Generated by Django 4.2.13 on 2024-07-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobutils', '0004_delete_educationlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblevel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='joblocation',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jobtiming',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
