# Generated by Django 4.1 on 2024-05-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('jobapply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsapply',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='users/jobseeker/coverletter'),
        ),
        migrations.AddField(
            model_name='jobsapply',
            name='cover_letter_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsapply',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_apply', to='resumes.resumes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsapply',
            name='email',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsapply',
            name='full_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsapply',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobsapply',
            name='phone_number',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
