# Generated by Django 4.2.13 on 2024-06-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        ('jobapply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsapply',
            name='cv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_apply', to='resumes.resumes'),
        ),
    ]
