# Generated by Django 4.2.13 on 2024-06-09 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('professions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='jobs/category/images')),
                ('is_popular', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='', max_length=250, null=True)),
                ('level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('', '')], default='', max_length=50, null=True)),
                ('location', models.CharField(choices=[('on_site', 'on_site'), ('remote', 'remote'), ('hybrid', 'hybrid'), ('', '')], default='', max_length=50, null=True)),
                ('required_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('timing', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'contract')], default='full_time', max_length=20)),
                ('salary_mode', models.CharField(choices=[('Annually', 'annually'), ('Hourly', 'hourly'), ('Monthly', 'monthly')], default='monthly', max_length=20)),
                ('min_salary', models.IntegerField(null=True)),
                ('max_salary', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='jobs/images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.jobcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='professions.profession')),
            ],
        ),
    ]
