# Generated by Django 4.2.13 on 2024-06-24 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobutils', '0002_delete_jobposition'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobutils.joblevel'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobutils.joblocation'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='timing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobutils.jobtiming'),
        ),
    ]
