# Generated by Django 4.1 on 2024-05-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
