# Generated by Django 4.1 on 2024-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobcategory_is_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='jobs',
            name='min_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='title',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
