# Generated by Django 4.2.13 on 2024-06-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobs_level_alter_jobs_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/category/images'),
        ),
    ]
