# Generated by Django 4.1 on 2024-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_salary_jobs_max_salary_jobs_min_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary_mode',
            field=models.CharField(choices=[('annually', 'annually'), ('hourly', 'hourly'), ('monthly', 'monthly')], default='monthly', max_length=20),
        ),
    ]
