# Generated by Django 4.1 on 2024-05-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='slug',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
