# Generated by Django 4.1 on 2024-05-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_jobcategory_slug_alter_profession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='image',
            field=models.ImageField(null=True, upload_to='profession/images'),
        ),
    ]
