# Generated by Django 4.1 on 2024-05-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0016_alter_professionalinformation_profession'),
        ('job', '0012_alter_profession_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
