# Generated by Django 4.1 on 2024-06-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
        ('job', '0015_alter_jobs_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='professions.profession'),
        ),
    ]
